name: Publish Release

on:
  push:
    tags:
      - "*"
permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 #v8.0.0
        with:
          version: "0.11.6"
          enable-cache: false

      - name: Set up Python 3.10
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: uv sync --locked --no-install-project

      - name: Test Code
        run: uv run pytest

  publish-pypi:
    runs-on: ubuntu-latest
    needs: [test]
    environment:
        name: pypi
        url: https://pypi.org/project/stwfsapy/
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 #v8.0.0
        with:
          version: "0.11.6"
          enable-cache: false

      - name: Set up Python 3.10
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
        with:
          python-version: '3.10'

      - name: Check version and build distribution
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          if [ $(uv version --short) != "${REF_NAME}" ]; then
            echo "The version specified in pyproject.toml and the tag name are not the same"
            echo "Will use the tag name as version name"
            uv version "${REF_NAME}"
          fi
          uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b #v1.14.0
